name: Data

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "*/5 * * * *"
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch data
      id: myRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://ws.audioscrobbler.com/2.0/?method=user.getinfo&user=neavepaul&api_key=${{ secrets.MUSIC_API }}&format=json'
        method: 'GET'
      
    - name: Update data file
      run: echo '${{ steps.myRequest.outputs.response }}' > data.json

    - name: Commit changed file
      uses: EndBug/add-and-commit@v7
      with:
        add: 'data.json'
        message: 'Updated listening data in data.json'
        
